name: Backup to R2

on:
  schedule:
    - cron: "0 0 1 * *" # Runs at midnight on the first day of every month
  workflow_dispatch:

jobs:
  back-up:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        repo:
          [
            "https://" + {{ secrets.BACKUP_PRIVATE_REPO_TOKEN }} + "@github.com/odelli/ipaddress.git",
            "https://" + {{ secrets.BACKUP_PRIVATE_REPO_TOKEN }} + "@github.com/odelli/aaal1986.git",
            "https://" + {{ secrets.BACKUP_PRIVATE_REPO_TOKEN }} + "@github.com/odelli/maxmind-api.git",
            "https://" + {{ secrets.BACKUP_PRIVATE_REPO_TOKEN }} + "@github.com/odelli/odelli.git",
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install @larose/git-backup
        run: npm install -g @larose/git-backup

      - name: Back up ${{ matrix.repo }}
        run: |
          git-backup snapshot \
            --repo ${{ matrix.repo }} \
            --remote ${{ secrets.REMOTE_ADDRESS }} \
            --access-key-id ${{ secrets.ACCESS_KEY_ID }} \
            --secret-access-key ${{ secrets.SECRET_ACCESS_KEY }}

          git-backup prune \
            --repo ${{ matrix.repo }} \
            --remote ${{ secrets.REMOTE_ADDRESS }} \
            --access-key-id ${{ secrets.ACCESS_KEY_ID }} \
            --secret-access-key ${{ secrets.SECRET_ACCESS_KEY }} \
            --retention-policy "daily=30"
